services:
  - type: web
    name: live-the-word
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false    # you'll set this in Render's dashboard
